
package GUI;

import napakalaki.BadConsequence;

/**
 *
 * @author alex
 */
public class PendingBadConsequence extends javax.swing.JPanel {
    
    private BadConsequence pending;
    
    /**
     * Creates new form PendingBadConsequence
     */
    public PendingBadConsequence() {
        initComponents();
    }

    public void setPendingBC(BadConsequence pending) {
        this.pending = pending;
        if(!pending.isEmpty())
            pendingbc.setText(pending.getText());
        else
            pendingbc.setText("No hay mal rollo por cumplir.");
        
        repaint();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pendingLabel = new javax.swing.JLabel();
        pendingbc = new javax.swing.JLabel();

        pendingLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        pendingLabel.setText("Mal rollo pendiente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pendingbc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(pendingLabel)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pendingLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pendingbc, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel pendingLabel;
    private javax.swing.JLabel pendingbc;
    // End of variables declaration//GEN-END:variables
}
