/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import napakalaki.Treasure;

/**
 *
 * @author alex
 */
public class TreasureView extends javax.swing.JPanel {
    
    private Treasure treasureModel;
    private boolean selected;
    Color preset;
    
    /**
     * Creates new form TreasureView
     */
    public TreasureView() {
        initComponents();
        selected = false;
        preset=bonus.getForeground();
    }

    public Treasure getTreasure() {
        return treasureModel;
    }

    public boolean isSelected() {
        return selected;
    }

    public void setTreasure(Treasure t) {
        treasureModel = t;
        name.setText(t.getName());
        type.setText(t.getType().toString());
        bonus.setText(Integer.toString(t.getBonus()));
        
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        bonusLabel = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        bonus = new javax.swing.JLabel();

        setBorder(null);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        name.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        name.setForeground(new java.awt.Color(25, 204, 2));
        name.setText("nombreTesoro");

        typeLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        typeLabel.setText("Tipo:");

        bonusLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        bonusLabel.setText("Bonus:");

        type.setText("jLabel4");

        bonus.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(typeLabel)
                        .addGap(18, 18, 18)
                        .addComponent(type)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(bonusLabel)
                        .addGap(18, 18, 18)
                        .addComponent(bonus)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeLabel)
                    .addComponent(type))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bonusLabel)
                    .addComponent(bonus))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        
        if(selected==true){
            selected=false;
            bonusLabel.setForeground(preset);
            bonus.setForeground(preset);
            type.setForeground(preset);
            typeLabel.setForeground(preset);
        } 
        else{
            selected=true;
            this.setBackground(Color.GRAY);
            bonusLabel.setForeground(Color.YELLOW);
            bonus.setForeground(Color.YELLOW);
            type.setForeground(Color.YELLOW);
            typeLabel.setForeground(Color.YELLOW);  
        }
        this.setOpaque(selected);
        repaint();
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bonus;
    private javax.swing.JLabel bonusLabel;
    private javax.swing.JLabel name;
    private javax.swing.JLabel type;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
}